---
title: "dgplyr"
format: html
editor: visual
toc:  true
lang: es
theme: yeti

---

## carga de paquetes

```{r}
#| label: carga-paquetes
#| message: false
#| warning: false

library(tidyverse)
library(DT)
library(gapminder)
library(ggthemes)
library(hrbrthemes)
```

## MPG

```{r}
#| label: tabla-mpg

mpg |>
  select(manufacturer, year, cty, hwy)|>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```


# diamonds
```{r}
#| label: tabla-diamonds

diamonds |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )

```
# gapminder
```{r}
#| label: tabla-gapminder

gapminder|>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )

```





# ggplot2

```{r}
#|label: ggplot2-1
ggplot( data = mpg)  + geom_point(aes(x=displ, y= hwy))
```

```{r}
#|label: ggplot2-01

mpg|>
  ggplot(aes(x= displ, y=hwy, colour = class)) +
  geom_point()
```
 
```{r}
#|label: ggplot2-01

mpg|>
  ggplot(aes(x= displ, y=hwy, shape = class, colour = class)) +
  geom_point()
```  


```{r}
#| label: ggplot-02

# Gráfico de dispersión de cilindrada vs millas por galón en autopista
# con formas y colores correspondientes al tipo de automóvil
mpg |>
  ggplot(aes(x = displ, y = hwy, shape = class, color = class)) +
  geom_point() +
  scale_shape_manual(values = c(0, 1, 2, 3, 4, 5, 6)) +
  scale_color_manual(values = c("red", "blue", "green", "purple", "orange", "brown", "pink"))
```
 
```{r}
#|label: ggplot2_06
#grafico de dispersion que muestre la racion entre el pib per capita x y esperanza de vida y

gapminder |>
  ggplot(aes(x = gdpPercap,y= lifeExp)) +
  geom_point()
```
 
 
```{r}
#|label: ggplot2-07
#|
#grafico de dispersion que muestre la racion entre el pib per capita x y esperanza de vida y

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap,y= lifeExp)) +
  geom_point()
```
```{r}
#|label: ggplot2-08
#grafico de dispersion que muestre la racion entre el pib per capita x y esperanza de vida y
#el PIB per capita

gapminder |>
  filter(year ==2007)|>
  ggplot(aes(x = gdpPercap,y= lifeExp, colour = continent)) +
  geom_point()

```
 
 
 
```{r}
#|label: ggplot2-08
#grafico de dispersion que muestre la racion entre el pib per capita x y esperanza de vida y
#el PIB per capita

gapminder |>
  filter(year ==2007)|>
  ggplot(aes(x = gdpPercap,y= lifeExp)) +
  geom_point() + geom_smooth(method = "lm")
```
 
 
```{r}
#|label: ggplot2-08
#|message: false
#|warning: false 
#grafico de dispersion que muestre la racion entre el pib per capita x y esperanza de vida y
#el PIB per capita

gapminder |>
  filter(year ==2007)|>
  ggplot(aes(x = gdpPercap,y= lifeExp, colour = continent)) +
  geom_point() + geom_smooth(method = "lm") +
  ggtitle("Relación entre PIB per capita y esperanza de vida en 2007") +
  xlab ("PIB per capita EEUU ($)") +
  ylab( "Esperanza de vida (años)") +
  theme_economist()
```
 
 